------------ Options -------------
anormly_ratio: 4.0
batch_size: 256
d_ff: 64
d_model: 64
data_path: ./dataset/SWaT
dataset: SWaT
dynamic_graph: True
e_layers: 1
fusion_method: weighted
gnn_heads: 2
gnn_hidden: 32
gnn_layers: 1
gnn_type: gatv2
input_c: 51
k: 3
k_neighbors: 2
lr: 0.0001
mode: train
model_save_path: ./checkpoints
model_type: advanced_transgnn
n_heads: 2
num_epochs: 5
output_c: 51
pretrained_model: None
residual: True
win_size: 30
-------------- End ----------------
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main(config)
  File "main.py", line 31, in main
    solver = Solver(vars(config))
  File "/root/autodl-tmp/Anomaly-Transformer-main/solver.py", line 73, in __init__
    self.train_loader = get_loader_segment(self.data_path, batch_size=self.batch_size, win_size=self.win_size,
TypeError: get_loader_segment() got an unexpected keyword argument 'num_workers'
